trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.auth_pkce_python.ini
  - name: analysisProject
    value: Auth_PKCE_Python

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          agentOS: Linux
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      # Adds chromedriver to path in Windows Command Prompt syntax
      - script: |
          echo Install chromedriver
          npm install chromedriver
          set PATH=%PATH%;$(Build.SourcesDirectory)\node_modules\chromedriver\lib\chromedriver
          echo Install test tools
          pip install pytest
          pip install selenium
          echo Install requirements
          pip install -r requirements.txt
          echo Run tests
          python -m pytest --junitxml=junit/test-results.xml  ./test.py
          echo Complete
        displayName: 'Run tests (Windows)'
        condition: eq(variables['Agent.OS'], 'Windows_NT')

      # Adds chromedriver to path in Linux bash syntax
      - script: |
          echo Install chromedriver
          npm install chromedriver
          export PATH=$PATH:$(Agent.WorkFolder)/node_modules/chromedriver/lib/chromedriver
          echo Install test tools
          pip install pytest
          pip install selenium
          echo Install requirements
          pip install -r requirements.txt
          echo Run tests
          python -m pytest --junitxml=junit/test-results.xml  ./test.py
          echo Complete
        displayName: 'Run tests (Linux)'
        condition: eq(variables['Agent.OS'], 'Linux')

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          useRequirementsTxt: true
