trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.auth_pkce_python.ini
  - name: analysisProject
    value: Auth_PKCE_Python

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - script: npm install chromedriver
        displayName: 'Install chromedriver'

      - script: |
          echo Install test tools
          pip install pytest
          pip install selenium
          echo Install requirements
          pip install -r requirements.txt
          echo Run tests
          python -m pytest --junitxml=junit/test-results.xml  ./test.py
          echo Complete
        env:
          PATH: $(PATH);$(Build.SourcesDirectory)\node_modules\chromedriver\lib\chromedriver
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - script: pip --version

      - script: |
          python ./pip-inspector.py --requirements=$(Build.SourcesDirectory)\requirements.txt

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          useRequirementsTxt: true
